// Code generated by MockGen. DO NOT EDIT.
// Source: props/types.go
//
// Generated by this command:
//
//	mockgen -source=props/types.go -destination=props/mocks/types.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	props "github.com/anyvoxel/airmid/props"
	gomock "go.uber.org/mock/gomock"
)

// MockProperties is a mock of Properties interface.
type MockProperties struct {
	ctrl     *gomock.Controller
	recorder *MockPropertiesMockRecorder
	isgomock struct{}
}

// MockPropertiesMockRecorder is the mock recorder for MockProperties.
type MockPropertiesMockRecorder struct {
	mock *MockProperties
}

// NewMockProperties creates a new mock instance.
func NewMockProperties(ctrl *gomock.Controller) *MockProperties {
	mock := &MockProperties{ctrl: ctrl}
	mock.recorder = &MockPropertiesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProperties) EXPECT() *MockPropertiesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProperties) Get(key string, opts ...props.GetOption) (any, error) {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPropertiesMockRecorder) Get(key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProperties)(nil).Get), varargs...)
}

// Set mocks base method.
func (m *MockProperties) Set(key string, val any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockPropertiesMockRecorder) Set(key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockProperties)(nil).Set), key, val)
}
