// Code generated by MockGen. DO NOT EDIT.
// Source: locator.go
//
// Generated by this command:
//
//	mockgen -source=locator.go -destination=locator_mocks_test.go -package=app
//

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResource is a mock of Resource interface.
type MockResource struct {
	ctrl     *gomock.Controller
	recorder *MockResourceMockRecorder
	isgomock struct{}
}

// MockResourceMockRecorder is the mock recorder for MockResource.
type MockResourceMockRecorder struct {
	mock *MockResource
}

// NewMockResource creates a new mock instance.
func NewMockResource(ctrl *gomock.Controller) *MockResource {
	mock := &MockResource{ctrl: ctrl}
	mock.recorder = &MockResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResource) EXPECT() *MockResourceMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockResource) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockResourceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockResource)(nil).Name))
}

// Read mocks base method.
func (m *MockResource) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockResourceMockRecorder) Read(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockResource)(nil).Read), p)
}

// MockResourceLocator is a mock of ResourceLocator interface.
type MockResourceLocator struct {
	ctrl     *gomock.Controller
	recorder *MockResourceLocatorMockRecorder
	isgomock struct{}
}

// MockResourceLocatorMockRecorder is the mock recorder for MockResourceLocator.
type MockResourceLocatorMockRecorder struct {
	mock *MockResourceLocator
}

// NewMockResourceLocator creates a new mock instance.
func NewMockResourceLocator(ctrl *gomock.Controller) *MockResourceLocator {
	mock := &MockResourceLocator{ctrl: ctrl}
	mock.recorder = &MockResourceLocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceLocator) EXPECT() *MockResourceLocatorMockRecorder {
	return m.recorder
}

// Locate mocks base method.
func (m *MockResourceLocator) Locate(filename string) ([]Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locate", filename)
	ret0, _ := ret[0].([]Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Locate indicates an expected call of Locate.
func (mr *MockResourceLocatorMockRecorder) Locate(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locate", reflect.TypeOf((*MockResourceLocator)(nil).Locate), filename)
}
