// Code generated by MockGen. DO NOT EDIT.
// Source: app/xapp.go
//
// Generated by this command:
//
//	mockgen -source=app/xapp.go -destination=app/xapp_mocks_test.go -package=app
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	ioc "github.com/anyvoxel/airmid/ioc"
	props "github.com/anyvoxel/airmid/ioc/props"
	gomock "go.uber.org/mock/gomock"
)

// MockApplication is a mock of Application interface.
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
	isgomock struct{}
}

// MockApplicationMockRecorder is the mock recorder for MockApplication.
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance.
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// AddBeanPostProcessor mocks base method.
func (m *MockApplication) AddBeanPostProcessor(beanPostProcessor ioc.BeanPostProcessor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBeanPostProcessor", beanPostProcessor)
}

// AddBeanPostProcessor indicates an expected call of AddBeanPostProcessor.
func (mr *MockApplicationMockRecorder) AddBeanPostProcessor(beanPostProcessor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBeanPostProcessor", reflect.TypeOf((*MockApplication)(nil).AddBeanPostProcessor), beanPostProcessor)
}

// Destroy mocks base method.
func (m *MockApplication) Destroy() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Destroy")
}

// Destroy indicates an expected call of Destroy.
func (mr *MockApplicationMockRecorder) Destroy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockApplication)(nil).Destroy))
}

// Get mocks base method.
func (m *MockApplication) Get(ctx context.Context, key string, opts ...props.GetOption) (any, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockApplicationMockRecorder) Get(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockApplication)(nil).Get), varargs...)
}

// GetBean mocks base method.
func (m *MockApplication) GetBean(ctx context.Context, name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBean", ctx, name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBean indicates an expected call of GetBean.
func (mr *MockApplicationMockRecorder) GetBean(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBean", reflect.TypeOf((*MockApplication)(nil).GetBean), ctx, name)
}

// GetBeanDefinition mocks base method.
func (m *MockApplication) GetBeanDefinition(beanName string) (ioc.BeanDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBeanDefinition", beanName)
	ret0, _ := ret[0].(ioc.BeanDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBeanDefinition indicates an expected call of GetBeanDefinition.
func (mr *MockApplicationMockRecorder) GetBeanDefinition(beanName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBeanDefinition", reflect.TypeOf((*MockApplication)(nil).GetBeanDefinition), beanName)
}

// PreInstantiateSingletons mocks base method.
func (m *MockApplication) PreInstantiateSingletons(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreInstantiateSingletons", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreInstantiateSingletons indicates an expected call of PreInstantiateSingletons.
func (mr *MockApplicationMockRecorder) PreInstantiateSingletons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreInstantiateSingletons", reflect.TypeOf((*MockApplication)(nil).PreInstantiateSingletons), ctx)
}

// PublishEvent mocks base method.
func (m *MockApplication) PublishEvent(ctx context.Context, event ApplicationEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishEvent", ctx, event)
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockApplicationMockRecorder) PublishEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEvent", reflect.TypeOf((*MockApplication)(nil).PublishEvent), ctx, event)
}

// RegisterBeanDefinition mocks base method.
func (m *MockApplication) RegisterBeanDefinition(beanName string, beanDefinition ioc.BeanDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterBeanDefinition", beanName, beanDefinition)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterBeanDefinition indicates an expected call of RegisterBeanDefinition.
func (mr *MockApplicationMockRecorder) RegisterBeanDefinition(beanName, beanDefinition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterBeanDefinition", reflect.TypeOf((*MockApplication)(nil).RegisterBeanDefinition), beanName, beanDefinition)
}

// RegisterScope mocks base method.
func (m *MockApplication) RegisterScope(name string, scope ioc.Scope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterScope", name, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterScope indicates an expected call of RegisterScope.
func (mr *MockApplicationMockRecorder) RegisterScope(name, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterScope", reflect.TypeOf((*MockApplication)(nil).RegisterScope), name, scope)
}

// RegisterSingleton mocks base method.
func (m *MockApplication) RegisterSingleton(name string, bean any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterSingleton", name, bean)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterSingleton indicates an expected call of RegisterSingleton.
func (mr *MockApplicationMockRecorder) RegisterSingleton(name, bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSingleton", reflect.TypeOf((*MockApplication)(nil).RegisterSingleton), name, bean)
}

// RemoveBeanDefinition mocks base method.
func (m *MockApplication) RemoveBeanDefinition(beanName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBeanDefinition", beanName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBeanDefinition indicates an expected call of RemoveBeanDefinition.
func (mr *MockApplicationMockRecorder) RemoveBeanDefinition(beanName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBeanDefinition", reflect.TypeOf((*MockApplication)(nil).RemoveBeanDefinition), beanName)
}

// ResolveBeanNames mocks base method.
func (m *MockApplication) ResolveBeanNames(ctx context.Context, typ reflect.Type) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveBeanNames", ctx, typ)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveBeanNames indicates an expected call of ResolveBeanNames.
func (mr *MockApplicationMockRecorder) ResolveBeanNames(ctx, typ any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveBeanNames", reflect.TypeOf((*MockApplication)(nil).ResolveBeanNames), ctx, typ)
}

// Run mocks base method.
func (m *MockApplication) Run(ctx context.Context, opts ...Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockApplicationMockRecorder) Run(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockApplication)(nil).Run), varargs...)
}

// Set mocks base method.
func (m *MockApplication) Set(ctx context.Context, key string, val any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockApplicationMockRecorder) Set(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockApplication)(nil).Set), ctx, key, val)
}

// Shutdown mocks base method.
func (m *MockApplication) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockApplicationMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockApplication)(nil).Shutdown))
}

// Submit mocks base method.
func (m *MockApplication) Submit(task func()) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submit indicates an expected call of Submit.
func (mr *MockApplicationMockRecorder) Submit(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockApplication)(nil).Submit), task)
}

// VisitBeanDefinition mocks base method.
func (m *MockApplication) VisitBeanDefinition(visitor ioc.BeanDefinitionVisitor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VisitBeanDefinition", visitor)
}

// VisitBeanDefinition indicates an expected call of VisitBeanDefinition.
func (mr *MockApplicationMockRecorder) VisitBeanDefinition(visitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitBeanDefinition", reflect.TypeOf((*MockApplication)(nil).VisitBeanDefinition), visitor)
}
